# Generated by Django 4.0.6 on 2022-07-11 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('pm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pm_description', models.TextField(blank=True, max_length=500, null=True)),
                ('pm_kind_of_activity', models.CharField(blank=True, max_length=150, null=True)),
                ('pm_interests', models.TextField(blank=True, max_length=300, null=True)),
                ('pm_place_of_work', models.CharField(blank=True, max_length=150, null=True)),
                ('pm_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('pm_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSocialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psm_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('psm_github', models.CharField(blank=True, max_length=200, null=True)),
                ('psm_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('psm', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprofile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='FollowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='sprofile.profilemodel')),
                ('p_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='sprofile.profilemodel')),
            ],
        ),
    ]
