# Generated by Django 4.0.6 on 2022-07-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pm_description',
            field=models.TextField(blank=True, default='Not specified.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='pm_interests',
            field=models.TextField(blank=True, default='Not specified.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='pm_kind_of_activity',
            field=models.CharField(blank=True, default='Not specified.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='pm_name',
            field=models.CharField(blank=True, default='Not specified.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='pm_place_of_work',
            field=models.CharField(blank=True, default='Not specified.', max_length=150, null=True),
        ),
    ]
